# 在文件顶部env部分添加：
env:
  DEFAULT_IP: 192.168.50.1
  DEFAULT_PWD: a5623141
  PPPOE_USER: 057179674959
  PPPOE_PASS: 760551
  TARGET: x86
  SUBTARGET: 64
  PROFILE: generic

# 在"Apply custom configurations"步骤中替换为：
- name: Apply custom configurations
  run: |
    # 修改默认IP和管理密码
    sed -i "s/192.168.1.1/${{ env.DEFAULT_IP }}/g" package/base-files/files/bin/config_generate
    sed -i "s/password/${{ env.DEFAULT_PWD }}/g" package/base-files/files/bin/config_generate
    
    # 添加第三方插件源
    echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> feeds.conf.default
    echo "src-git openclash https://github.com/vernesong/OpenClash" >> feeds.conf.default
    echo "src-git vlmcsd https://github.com/cokebar/openwrt-vlmcsd" >> feeds.conf.default
    
    # 更新feeds
    ./scripts/feeds update -a
    ./scripts/feeds install -a
    
    # 创建预置配置文件目录
    mkdir -p files/etc/config
    
    # 配置WAN口为eth0
    cat > files/etc/config/network <<EOF
config interface 'wan'
        option ifname 'eth0'
        option proto 'pppoe'
        option username '${{ env.PPPOE_USER }}'
        option password '${{ env.PPPOE_PASS }}'
        option ipv6 'auto'
        
config interface 'lan'
        option type 'bridge'
        option ifname 'eth1'
        option proto 'static'
        option netmask '255.255.255.0'
        option ipaddr '${{ env.DEFAULT_IP }}'
EOF

    # 启用uhttpd HTTPS
    cat > files/etc/config/uhttpd <<EOF
config uhttpd 'main'
        option listen_http '0.0.0.0:80'
        option listen_https '0.0.0.0:443'
        option redirect_https '1'
        option home '/www'
        option cert '/etc/uhttpd.crt'
        option key '/etc/uhttpd.key'
EOF
    
    # 生成自签名证书
    mkdir -p files/etc
    openssl req -new -x509 -nodes -days 365 -out files/etc/uhttpd.crt -keyout files/etc/uhttpd.key -subj "/CN=openwrt"
    
    # 设置Alpha为默认主题
    cat > files/etc/config/luci <<EOF
config core 'main'
        option lang 'auto'
        option resourcebase '/luci-static/resources'
        option mediaurlbase '/luci-static/alpha'

config extern 'flash_keep'
        option uci '/etc/config/'

config internal 'languages'
        option zh_cn '简体中文 (Simplified Chinese)'

config internal 'sauth'
        option sessionpath '/tmp/luci-sessions'
        option sessiontime '3600'

config internal 'themes'
        option Alpha '/luci-static/alpha'
EOF

# 在"Apply custom .config"步骤中替换为：
- name: Apply custom .config
  run: |
    cat > .config <<EOF
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_Generic=y

# 生成EFI镜像
CONFIG_GRUB_IMAGES=y
CONFIG_GRUB_EFI_IMAGES=y
CONFIG_VDI_IMAGES=n
CONFIG_VMDK_IMAGES=n
CONFIG_ISO_IMAGES=y

# IPv6支持
CONFIG_PACKAGE_ipv6helper=y
CONFIG_PACKAGE_dnsmasq_full_ipv6=y
CONFIG_PACKAGE_odhcp6c=y

# 指定插件
CONFIG_PACKAGE_open-vm-tools=y
CONFIG_PACKAGE_luci-theme-alpha=y
CONFIG_PACKAGE_luci-app-vlmcsd=y
CONFIG_PACKAGE_luci-app-ttyd=y
CONFIG_PACKAGE_luci-app-turboacc=y
CONFIG_PACKAGE_luci-app-openclash=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-app-uhttpd=y

# uhttpd HTTPS
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_libustream-openssl=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y

# 其他依赖
CONFIG_PACKAGE_luci-lib-ipkg=y
CONFIG_PACKAGE_ttyd=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_kmod-ipt-nat6=y
EOF
    
    make defconfig
